template-file-path: infra-redshift-dl-test.yaml
parameters: {}
tags: {}

AWSTemplateFormatVersion: '2010-09-09'
Description: Template to create an S3 bucket

Resources:
  MyS3Bucket:
    Type: 'AWS::S3::Bucket'
    Properties:
      BucketName: !Sub 'infra-redshift-dl-test-316328384763-us-east-1'

Outputs:
  BucketName:
    Description: The name of the S3 bucket
    Value: !Ref MyS3Bucket
