Description: "Create a CodeStar Sync Configuration for the Deploy Codepipeline (v1.0.0)"
Parameters:
  # General Configuration
  SuggestedStackName:
    Type: "String"
    Description: "If creating through the AWS Console, this is the suggested stack name.  Copy and paste this value for the stack name."
    Default: "redshift-dl-deploy-sync-configuration"
  BranchName:
    Type: "String"
    Description: "The name of the Git branch to use."
    Default: "main"
  ConfigFile:
    Type: "String"
    Description: "The relative path and name of deployment configuration file."
    Default: "/infra-redshift-dl-test/deployment/datalake/deploy.yaml" 
  ResourceName:
    Type: "String"
    Description: "The name of the parent stack."
    Default: "redshift-dl-deploy-git-sync-stack" #Must match the name of the parent template stack.
Resources:
  GitHubSyncConfiguration:
    Type: "AWS::CodeStarConnections::SyncConfiguration"
    Properties:
      RepositoryLinkId: "275fdc01-3b33-48c3-b685-0eea5d3f764b" #From connection.yaml
      RoleArn: "arn:aws:iam::316328384763:role/git-sync-role-us-east-1" #From git-sync.yaml
      Branch: !Ref BranchName
      ConfigFile: !Ref ConfigFile
      ResourceName: !Ref ResourceName
      SyncType: "CFN_STACK_SYNC"
Outputs:
  GitHubSyncConfigurationArn:
    Description: "The Git Sync Configuration ARN."
    Value: !Ref GitHubSyncConfiguration
    Export:
      Name: !Sub "${AWS::StackName}-GitHubSyncConfigurationArn"
Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
    - Label:
        default: "General Configuration"
      Parameters:
      - SuggestedStackName
      - BranchName
      - ConfigFile
      - ResourceName
    ParameterLabels:
      # General Configuration
      SuggestedStackName:
        default: "Suggested Stack Name:"
      BranchName:
        default: "Git Branch Name:"
      ConfigFile:
        default: "Config File Name:"
      ResourceName:
        default: "Resource Name:"